"""initial migration

Revision ID: 507c31cc57cf
Revises: 
Create Date: 2024-11-17 23:50:02.032980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507c31cc57cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.String(length=10), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('author_dob', sa.Date(), nullable=False),
    sa.Column('author_origin', sa.Text(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('employee_name', sa.String(length=50), nullable=False),
    sa.Column('employee_email', sa.String(length=50), nullable=False),
    sa.Column('employee_phone', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('member',
    sa.Column('member_id', sa.String(length=10), nullable=False),
    sa.Column('member_name', sa.String(length=50), nullable=False),
    sa.Column('member_type', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('member_course', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('street', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.String(length=10), nullable=False),
    sa.Column('publisher_name', sa.String(length=50), nullable=False),
    sa.Column('publisher_address', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_table('shelf',
    sa.Column('shelf_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shelf_floor', sa.Integer(), nullable=False),
    sa.Column('shelf_rows', sa.Integer(), nullable=False),
    sa.Column('shelf_cols', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shelf_id')
    )
    op.create_table('vendor',
    sa.Column('vendor_id', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=50), nullable=False),
    sa.Column('vendor_address', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.String(length=10), nullable=False),
    sa.Column('author_id', sa.String(length=10), nullable=False),
    sa.Column('book_title', sa.String(length=80), nullable=False),
    sa.Column('publisher_id', sa.String(length=10), nullable=False),
    sa.Column('vendor_id', sa.String(length=10), nullable=False),
    sa.Column('shelf_id', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('date_of_publishing', sa.Date(), nullable=False),
    sa.Column('date_of_addition', sa.Date(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('shelf_date', sa.Date(), nullable=False),
    sa.Column('bought_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelf.shelf_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('fine',
    sa.Column('fine_id', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('days_delay', sa.Date(), nullable=False),
    sa.Column('member_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fine_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.String(length=10), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('member_id', sa.String(length=10), nullable=False),
    sa.Column('book_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('fine')
    op.drop_table('book')
    op.drop_table('vendor')
    op.drop_table('shelf')
    op.drop_table('publisher')
    op.drop_table('member')
    op.drop_table('employee')
    op.drop_table('author')
    # ### end Alembic commands ###
